settings:
  title: 'Are My services alright?'
  url: 'https://status.mitt.fun' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: blog-mitt-fun
    name: Mitt's Blog
    url: 'https://blog.mitt.fun/'
    method: GET
    expectStatus: 200
    
  - id: workers-friends # unique identifier
    name: Mitt's Friends redirector
    url: 'https://friends.mitt.fun/mitt' # URL to fetch
    method: GET # default=GET
    expectStatus: 302 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: pwecho-com
    name: ECHO Platform
    description: 'for co-game serve platform.'
    url: 'https://pwecho.com'
    method: HEAD
    expectStatus: 200

